### ISSUE TITLE
Remember history of commands

### ISSUE THREAD

**Issue by temoto** [markbirbeck/sublime-text-shell-command#27]
Command history with up/down choice would greatly improve user experience
- Ctrl+R search in history, like in terminal shell
- open command dialog with previous command entered and selected, so that just Enter will repeat previous command but any other key will start entering new command from scratch

**Comment by flriancu** [comment]
I second this. It would be an incredibly useful addition to a great plugin.

**Comment by rodvlopes** [comment]
Ctrl+r is would be awsome. Up and down arrow to navigate throgh history too.

**Comment by frizop** [comment]
It's mentioned here: http://www.sublimetext.com/forum/viewtopic.php?f=6&t=14777&p=59099&hilit=show_input_panel#p59099 if anybody is interested in implementing this. I'd love to see it.

**Comment by kaste** [comment]
PTAL at #56
