### ISSUE TITLE
Allow user to enter values that will be used in commands

### ISSUE THREAD

**Issue by markbirbeck** [markbirbeck/sublime-text-shell-command#36]
Often commands such as renaming a Git branch will require input from the user. This feature will allow variables to be provided by the user using the dollar syntax and a string to indicate the command prompt.

The following example shows how this feature could be used to create a shortcut that allows a feature branch to be started that uses a name for the new branch that is provided by the user:

```json
[
  {
    "keys": ["!", "f"],
    "command": "shell_command",
    "args": {
      "command": "git checkout -b feature/${branch::Feature Branch} develop",
      "panel": true
    }
  }
]
```

Note that the double colon in the middle indicates that there is no default value. If one was provided then this would be used to populate the prompt first:

```
git checkout -b feature/${branch:my new feature:Feature Branch} develop
```

**Comment by markbirbeck** [comment]
Implemented in 947b854.

**Comment by markbirbeck** [comment]
This implements @aflc's PR #7.

**Comment by markbirbeck** [comment]
This also answers one part of @pchomik's request at https://github.com/wbond/package_control_channel/pull/3835.

**Comment by p3lim** [comment]
Is it possible to use the same input more than once in the command?

For example, I'd like to set up a key binding to make tags easier, like so:
    git tag -m "Tag ${tag::Tag}" ${tag::Tag}

Basically using the input for both the tag message and the actual tag in one.
