### ISSUE TITLE
enable scrolling to end on long output

### ISSUE THREAD

**Issue by PeterPablo** [markbirbeck/sublime-text-shell-command#39]
Please add an option that allows to enable/disable the scrolling of the output (buffer or panel). I am commonly starting a compilation with large output and would like to see the end to easily see, when it finishes/fails.

**Comment by markbirbeck** [comment]
I've decided to implement this by copying the Emacs `comint-scroll-show-maximum-output` variable. From the Emacs documentation:

> If comint-scroll-show-maximum-output is non-nil, then scrolling due to arrival of output tries to place the last line of text at the bottom line of the window, so as to show as much useful text as possible. (This mimics the scrolling behavior of many terminals.) The default is nil.

I think that pretty much captures what we want.

**Comment by PeterPablo** [comment]
Works as promised :+1: 
Thank you!
