### ISSUE TITLE
How do I pass the selected files path as an argument?

### ISSUE THREAD

**Issue by stephenmfriend** [markbirbeck/sublime-text-shell-command#49]
I might be missing something when trawling the docs but is it possible to pass the selected file path/name as an argument rather than the regions selection? E.g. Where ${filename} is the complete pathname of the selected file?

```json
[
    {
        "keys": ["ctrl+enter"],
        "command": "shell_command",
        "args": {
            "command": "~/Scripts/MyScript.sh -c ${configFile::Config File} -i ${filename}",
            "title": "Script Output",
        },
    }
]
```

Thanks.

**Comment by sntran** [comment]
:+1: 

Also, would be nice if we can have the line number under the selection as argument too.

**Comment by connected** [comment]
@stephenmfriend, sometimes digging the source files pays off :)

If you look at the [VariableSubstitution.py](https://github.com/markbirbeck/sublime-text-shell-command/blob/master/VariableSubstitution.py#L36) file you can see that number of variables are exposed to command that you can use!

I've updated [docs](https://github.com/connected/sublime-text-shell-command/tree/patch-1#user-content-predefined-variables) and created a [pull request](https://github.com/markbirbeck/sublime-text-shell-command/pull/57) for this.

Cheers.

**Comment by blutsvente** [comment]
Related to this, how can I use ${file} or such in a command that has been entered at the prompt? Basically I need a "shell_command_on_file" where the user enters the command and sublime executes it with the filename as argument. It tried
```
args: {
  "prompt": "Command on file:",
  "stdin": "${file}"
}
```
But this does not work.

**Comment by blutsvente** [comment]
Answering myself: ShellCommand prompts for any undefined variables in the command, so
```
"args" : {
  "command" : "${xcmd::Shell command on file} ${file}"
}
```
will do the trick. Here I use that `${...}` can be also `${<var-name>:<default>:<prompt-string>}`.

**Comment by jdarais** [comment]
Being able to substitute the current file name into a command is a great feature.  Any reason why variables are substituted in pre-defined commands, but not in commands entered at the prompt?  Looks like blutsvente has a workaround that works for some things, but general variable substitution would be much more flexible.

**Comment by markbirbeck** [comment]
Looks like this is resolved.
