### ISSUE TITLE
Documentation is not clear on which files to add commands to

### ISSUE THREAD

**Issue by joeparkerz** [markbirbeck/sublime-text-shell-command#59]
You don't actually specify where do you put the commands in? There are three files.

Puting this in either of them does not work.

```json
[
  {
    "keys": ["ctrl+enter"],
    "command": "shell_command",
    "args": {
      "prompt": "Enter a command",
      "title": "My Command"
    }
  }
]
```

- ShellCommand.sublime-commands
- ShellCommand.sublime-keymap
- ShellCommand.sublime-settings

**Comment by jcrben** [comment]
Yeah, I got confused and couldn't get my commands to fire.

**Comment by DiegoAz** [comment]
@joeparkerz @jcrben you need to put the commands in the **Default (_your OS here_).sublime-keymap** file. I remember that SublimeText previously let the plugins manage key bindings in .sublime-keymap files, but 
I do not remember from which version all the key bindings are defined in the Default.sublime-keymap file. You can open that file from the menu: Preferences/Key Bindings

**Comment by DiegoAz** [comment]
@jcrben I don't see the relationship between the fact that vscode is open source and this issue. Like Shell Command at https://packagecontrol.io reside numerous open source packages hosted on Github that makes Sublime Text better for many people. This package that don't have a direct relationship with the Sublime Text team has not been updated for 2 years which can generate frustration to new users, but when people got confused about something that is not answered on the corresponding issues section, they can visit the [sublime text forum](https://forum.sublimetext.com) where someone can help.

**Comment by jcrben** [comment]
Well, when I commented over a year ago, I said this:
> If Sublime was open-source, I might have dug in to figure it out...
When I run into issues like this these days with vscode, I open up the devtools and see what's going on in the code. Can't really do that with the code.

I'm not sure how you figured out the solution - but without access to the code I feel a bit like I'm stumbling in the dark. Don't have time for that. 😄 

> people got confused about something that is not answered on the corresponding issues section, they can visit the sublime text forum where someone can help.
If people don't have access to the code, it's less easy to provide answers.

**Comment by DiegoAz** [comment]
> I'm not sure how you figured out the solution

Like I said:

> SublimeText previously let the plugins manage key bindings in .sublime-keymap files, but
I do not remember from which version all the key bindings are defined in the Default.sublime-keymap file.

In this case you needed to know that from the corresponding ST changelog or by using ST, due to the ShellCommand documentation don't mention it

This being an external package to ST, you have the code to check out here on Github, as with the other packages you found at [package control](https://packagecontrol.io). ST provides an [API](https://www.sublimetext.com/docs/3/api_reference.html) and [documentation](https://www.sublimetext.com/docs/3/) that the packages creators use to create the different packages.

**Comment by markbirbeck** [comment]
I've opened #67 to resolve this.
