### ISSUE TITLE
setting panel option still results in output to window

### ISSUE THREAD

**Issue by neins** [markbirbeck/sublime-text-shell-command#80]
I used these key settings:
```json
{
  "keys": ["ctrl+enter"],
  "command": "shell_command",
  "args": {
    "panel": true,
    "command_prefix": "git",
    "prompt": "Git Command"
  }
}
```

But i got a window insted a panel:

![image](https://user-images.githubusercontent.com/22091732/61176196-44a03080-a5c5-11e9-87a0-44079d20d725.png)

**Comment by yaroslavyaroslav** [comment]
@markbirbeck there's still a buggy version in package control due to there were no new version tagged after merging this.
