### ISSUE TITLE
Allow the output of a command to overwrite the region used as input

### ISSUE THREAD

**Issue by markbirbeck** [markbirbeck/sublime-text-shell-command#9]
In Emacs this is achieved by prefixing `shell-command` and `shell-command-on-region` with `[CTRL]+U`.

**Comment by thecotne** [comment]
+1

**Comment by rodvlopes** [comment]
:+1: This is also possible in VIM and it is useful

**Comment by mwick83** [comment]
I'm trying to move away from good old nedit, where I use this feature a lot with shell-scripts and external perl scripts, which basically do: pipe selection to STDIN, run script and replace selection with STDOUT. Messages from the script (STDERR) should go to a panel.

As far as I can see, only replacing the selection with STDOUT is currently missing. So, a

+1

from me, too.

**Comment by cormullion** [comment]
Before finding this I asked about similar functionality on [SublimeText's forum](https://forum.sublimetext.com/t/replace-text-by-running-external-command-like-vims-range-script). I think this package could be the missing link, if replacing the input region was added! So +1 from me too.

**Comment by markbirbeck** [comment]
Sorry this took over 2 years!

@cormullion: Perhaps you could answer your question in the forum with a link to the plugin on Package Control? Perhaps we can get a few more downloads. ;)

**Comment by cormullion** [comment]
@markbirbeck  Awesome! (I didn't notice the wait :) !) I'll give it a thorough workout tomorrow. In advance -- thanks!
